 2021-02-05 12:20:31,687 [P10728/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.12.1 application starting on MICROSOFT-PC
 2021-02-05 12:20:31,718 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2021-02-05 12:20:31,729 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 11ms)
 2021-02-05 12:20:31,816 [P10728/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2021-02-05 12:20:31,818 [P10728/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2021-02-05 12:20:31,820 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:32,271 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 450ms)
 2021-02-05 12:20:32,271 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2021-02-05 12:20:32,284 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 13ms)
 2021-02-05 12:20:32,309 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:32,310 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:20:32,310 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2021-02-05 12:20:32,320 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 9ms)
 2021-02-05 12:20:32,320 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:32,321 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:20:32,321 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2021-02-05 12:20:32,331 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 9ms)
 2021-02-05 12:20:32,347 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:32,348 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:20:32,348 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2021-02-05 12:20:32,362 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 13ms)
 2021-02-05 12:20:32,363 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:32,363 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:20:32,363 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2021-02-05 12:20:32,371 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 8ms)
 2021-02-05 12:20:34,053 [P10728/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2021-02-05 12:20:34,237 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2021-02-05 12:20:34,249 [P10728/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 12ms)
 2021-02-05 12:20:34,327 [P10728/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2021-02-05 12:20:34,528 [P10728/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2021-02-05 12:20:34,529 [P10728/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2021-02-05 12:20:34,542 [P10728/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 2962ms)
 2021-02-05 12:20:34,546 [P10728/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalMemberIndexSet to be unlocked since it was left in a locked state
 2021-02-05 12:20:34,547 [P10728/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 12:20:34,548 [P10728/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index ExternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 12:20:34,788 [P10728/D2/T10] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost/umbraco
 2021-02-05 12:20:34,793 [P10728/D2/T10] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2021-02-05 12:20:46,744 [P10728/D2/T10] INFO  umbraco.content - Load Xml from file...
 2021-02-05 12:20:46,749 [P10728/D2/T10] INFO  umbraco.content - Loaded Xml from file.
 2021-02-05 12:20:47,391 [P10728/D2/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:47,392 [P10728/D2/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:20:47,392 [P10728/D2/T10] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 12:20:47,405 [P10728/D2/T10] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 13ms)
 2021-02-05 12:20:47,421 [P10728/D2/T7] INFO  Umbraco.Core.Manifest.ManifestWatcher - manifest has changed, app pool is restarting (C:\Users\User_2\source\repos\TestProject\TestProject\App_Plugins\DocTypeGridEditor\package.manifest)
 2021-02-05 12:20:47,441 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Terminating
 2021-02-05 12:20:47,441 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Waiting for tasks to complete
 2021-02-05 12:20:47,446 [P10728/D2/T11] INFO  Umbraco.Core.MainDom - Stopping...
 2021-02-05 12:20:47,449 [P10728/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Tasks completed, terminated
 2021-02-05 12:20:47,450 [P10728/D2/T11] INFO  Umbraco.Web.ExamineStartup - Examine shutting down
 2021-02-05 12:20:47,456 [P10728/D2/T11] INFO  Umbraco.Web.ExamineStartup - Complete (took 5ms)
 2021-02-05 12:20:47,457 [P10728/D2/T11] INFO  Umbraco.Core.MainDom - Released MainDom.
 2021-02-05 12:20:47,457 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Terminating
 2021-02-05 12:20:47,457 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Waiting for tasks to complete
 2021-02-05 12:20:47,457 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Terminating
 2021-02-05 12:20:47,458 [P10728/D2/T14] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Tasks completed, terminated
 2021-02-05 12:20:47,458 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Waiting for tasks to complete
 2021-02-05 12:20:47,458 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Terminating
 2021-02-05 12:20:47,459 [P10728/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Tasks completed, terminated
 2021-02-05 12:20:47,459 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Waiting for tasks to complete
 2021-02-05 12:20:47,460 [P10728/D2/T16] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Tasks completed, terminated
 2021-02-05 12:20:47,461 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Terminating
 2021-02-05 12:20:47,462 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Waiting for tasks to complete
 2021-02-05 12:20:47,462 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Terminating
 2021-02-05 12:20:47,462 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Waiting for tasks to complete
 2021-02-05 12:20:47,463 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Terminating
 2021-02-05 12:20:47,463 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Waiting for tasks to complete
 2021-02-05 12:20:47,462 [P10728/D2/T14] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Tasks completed, terminated
 2021-02-05 12:20:47,463 [P10728/D2/T11] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Tasks completed, terminated
 2021-02-05 12:20:47,463 [P10728/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Tasks completed, terminated
 2021-02-05 12:20:53,497 [P10728/D3/T17] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.12.1 application starting on MICROSOFT-PC
 2021-02-05 12:20:53,528 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2021-02-05 12:20:53,540 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Hash determined (took 12ms)
 2021-02-05 12:20:53,617 [P10728/D3/T17] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2021-02-05 12:20:53,619 [P10728/D3/T17] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2021-02-05 12:20:53,621 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:54,236 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 615ms)
 2021-02-05 12:20:54,237 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2021-02-05 12:20:54,238 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 1ms)
 2021-02-05 12:20:54,297 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:54,298 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:20:54,298 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2021-02-05 12:20:54,299 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2021-02-05 12:20:54,299 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:54,300 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:20:54,300 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2021-02-05 12:20:54,302 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 2ms)
 2021-02-05 12:20:54,322 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:54,323 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:20:54,323 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2021-02-05 12:20:54,323 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 0ms)
 2021-02-05 12:20:54,325 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:20:54,325 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:20:54,325 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2021-02-05 12:20:54,327 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 1ms)
 2021-02-05 12:20:56,651 [P10728/D3/T17] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2021-02-05 12:20:57,040 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2021-02-05 12:20:57,118 [P10728/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 78ms)
 2021-02-05 12:20:57,254 [P10728/D3/T17] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2021-02-05 12:20:57,736 [P10728/D3/T17] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2021-02-05 12:20:57,737 [P10728/D3/T17] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2021-02-05 12:20:57,751 [P10728/D3/T17] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 4395ms)
 2021-02-05 12:21:00,820 [P10728/D3/T13] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost/umbraco
 2021-02-05 12:21:00,822 [P10728/D3/T13] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2021-02-05 12:21:00,822 [P10728/D3/T14] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2021-02-05 12:21:04,440 [P10728/D3/T13] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:04,441 [P10728/D3/T13] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:04,441 [P10728/D3/T13] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 12:21:04,465 [P10728/D3/T13] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 24ms)
 2021-02-05 12:21:06,037 [P10728/D3/T16] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:06,038 [P10728/D3/T16] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:06,038 [P10728/D3/T16] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2021-02-05 12:21:06,060 [P10728/D3/T16] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 22ms)
 2021-02-05 12:21:06,217 [P10728/D3/T16] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:06,218 [P10728/D3/T16] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:06,218 [P10728/D3/T16] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 12:21:06,219 [P10728/D3/T16] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 0ms)
 2021-02-05 12:21:10,190 [P10728/D3/T16] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username test@test.test from IP address ::1
 2021-02-05 12:21:10,192 [P10728/D3/T16] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: test@test.test logged in from IP address ::1
 2021-02-05 12:21:10,677 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:10,678 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:10,678 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2021-02-05 12:21:10,692 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 14ms)
 2021-02-05 12:21:10,715 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:10,715 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:10,716 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 12:21:10,716 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2021-02-05 12:21:10,721 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:10,721 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:10,722 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2021-02-05 12:21:10,740 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 18ms)
 2021-02-05 12:21:10,761 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:10,762 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:10,762 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2021-02-05 12:21:10,780 [P10728/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 17ms)
 2021-02-05 12:21:11,028 [P10728/D3/T13] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:11,029 [P10728/D3/T13] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:11,030 [P10728/D3/T13] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2021-02-05 12:21:11,050 [P10728/D3/T13] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 20ms)
 2021-02-05 12:21:15,197 [P10728/D3/T20] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:15,198 [P10728/D3/T20] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:15,198 [P10728/D3/T20] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.HealthCheck.HealthCheck
 2021-02-05 12:21:15,215 [P10728/D3/T20] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.HealthCheck.HealthCheck (took 17ms)
 2021-02-05 12:21:17,552 [P10728/D2/T14] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: UnloadAppDomainCalled

_shutDownMessage=User code called UnloadAppDomain
HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown

_shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   at System.Web.HttpRuntime.UnloadAppDomain()
   at Umbraco.Core.Manifest.ManifestWatcher.FswChanged(Object sender, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
 2021-02-05 12:21:21,923 [P10728/D3/T9] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:21:21,923 [P10728/D3/T9] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:21:21,923 [P10728/D3/T9] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 12:21:21,923 [P10728/D3/T9] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 0ms)
 2021-02-05 12:21:25,890 [P10728/D3/T10] INFO  umbraco.content - Load Xml from file...
 2021-02-05 12:21:25,892 [P10728/D3/T10] INFO  umbraco.content - Loaded Xml from file.
 2021-02-05 12:22:06,038 [P10728/D3/T11] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2021-02-04 12:22:06
 2021-02-05 12:22:10,056 [P10728/D3/T23] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 12:25:40,960 [P10728/D3/T32] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2021-02-05 12:26:54,458 [P10728/D3/T32] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:26:54,459 [P10728/D3/T32] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:26:54,459 [P10728/D3/T32] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Editors.IEditorValidator
 2021-02-05 12:26:54,492 [P10728/D3/T32] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Editors.IEditorValidator (took 32ms)
 2021-02-05 12:26:54,612 [P10728/D3/T32] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:26:54,612 [P10728/D3/T32] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:26:54,612 [P10728/D3/T32] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2021-02-05 12:26:54,622 [P10728/D3/T32] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 9ms)
 2021-02-05 12:26:54,706 [P10728/D3/T32] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generate models now.
 2021-02-05 12:26:58,983 [P10728/D3/T32] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generated.
 2021-02-05 12:27:01,402 [P10728/D3/T41] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2021-02-05 12:27:11,132 [P10728/D3/T40] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2021-02-05 12:27:14,191 [P10728/D3/T42] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 12:27:36,399 [P10728/D3/T32] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2021-02-05 12:27:41,120 [P10728/D3/T34] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generate models now.
 2021-02-05 12:27:41,246 [P10728/D3/T34] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generated.
 2021-02-05 12:28:41,607 [P10728/D3/T32] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2021-02-05 12:28:49,605 [P10728/D3/T39] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2021-02-05 12:32:36,162 [P12244/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.12.1 application starting on MICROSOFT-PC
 2021-02-05 12:32:36,215 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2021-02-05 12:32:36,246 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 31ms)
 2021-02-05 12:32:36,383 [P12244/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2021-02-05 12:32:36,386 [P12244/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2021-02-05 12:32:36,388 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:32:36,935 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 545ms)
 2021-02-05 12:32:36,936 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2021-02-05 12:32:36,952 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 16ms)
 2021-02-05 12:32:36,983 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:32:36,984 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2021-02-05 12:32:36,984 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2021-02-05 12:32:36,999 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 15ms)
 2021-02-05 12:32:37,000 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:32:37,001 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:32:37,001 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2021-02-05 12:32:37,016 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 15ms)
 2021-02-05 12:32:37,042 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:32:37,043 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:32:37,043 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2021-02-05 12:32:37,054 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 11ms)
 2021-02-05 12:32:37,056 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:32:37,056 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:32:37,056 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2021-02-05 12:32:37,069 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 12ms)
 2021-02-05 12:32:39,155 [P12244/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2021-02-05 12:32:39,385 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2021-02-05 12:32:39,403 [P12244/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 18ms)
 2021-02-05 12:32:39,508 [P12244/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2021-02-05 12:32:40,092 [P12244/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2021-02-05 12:32:40,095 [P12244/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2021-02-05 12:32:40,108 [P12244/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 4052ms)
 2021-02-05 12:32:40,116 [P12244/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalMemberIndexSet to be unlocked since it was left in a locked state
 2021-02-05 12:32:40,118 [P12244/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 12:32:40,120 [P12244/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index ExternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 12:32:40,386 [P12244/D2/T7] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost/umbraco
 2021-02-05 12:32:40,388 [P12244/D2/T7] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2021-02-05 12:32:47,111 [P12244/D2/T7] INFO  umbraco.content - Load Xml from file...
 2021-02-05 12:32:47,126 [P12244/D2/T7] INFO  umbraco.content - Loaded Xml from file.
 2021-02-05 12:32:47,871 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:32:47,872 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:32:47,872 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 12:32:47,889 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 17ms)
 2021-02-05 12:33:11,717 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:33:11,717 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:33:11,718 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 12:33:11,737 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 19ms)
 2021-02-05 12:33:11,879 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:33:11,881 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2021-02-05 12:33:11,881 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2021-02-05 12:33:11,898 [P12244/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 17ms)
 2021-02-05 12:33:12,624 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:33:12,624 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:33:12,625 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2021-02-05 12:33:12,637 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 12ms)
 2021-02-05 12:33:12,659 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:33:12,660 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:33:12,660 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 12:33:12,660 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2021-02-05 12:33:12,665 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:33:12,665 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:33:12,665 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2021-02-05 12:33:12,680 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 14ms)
 2021-02-05 12:33:12,704 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:33:12,704 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:33:12,704 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2021-02-05 12:33:12,722 [P12244/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 17ms)
 2021-02-05 12:33:13,306 [P12244/D2/T16] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:33:13,306 [P12244/D2/T16] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:33:13,307 [P12244/D2/T16] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2021-02-05 12:33:13,321 [P12244/D2/T16] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 14ms)
 2021-02-05 12:33:40,390 [P12244/D2/T16] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:33:40,548 [P12244/D2/T16] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:33:40,549 [P12244/D2/T16] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:33:40,549 [P12244/D2/T16] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2021-02-05 12:33:40,563 [P12244/D2/T16] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 14ms)
 2021-02-05 12:33:44,643 [P12244/D2/T7] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:33:44,673 [P12244/D2/T7] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:33:47,203 [P12244/D2/T7] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2021-02-04 12:33:47
 2021-02-05 12:33:51,253 [P12244/D2/T19] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 12:36:33,252 [P12244/D2/T15] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:36:37,362 [P12244/D2/T7] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:36:37,376 [P12244/D2/T7] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:38:38,022 [P12244/D2/T12] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:38:42,115 [P12244/D2/T7] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:38:42,132 [P12244/D2/T7] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:38:55,364 [P12244/D2/T67] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 12:40:56,855 [P12244/D2/T90] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 12:40:56,856 [P12244/D2/T90] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 12:40:56,856 [P12244/D2/T90] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.HealthCheck.HealthCheck
 2021-02-05 12:40:56,887 [P12244/D2/T90] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.HealthCheck.HealthCheck (took 31ms)
 2021-02-05 12:41:22,117 [P12244/D2/T7] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generate models now.
 2021-02-05 12:41:23,414 [P12244/D2/T7] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generated.
 2021-02-05 12:41:39,395 [P12244/D2/T92] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:41:43,491 [P12244/D2/T72] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:41:43,508 [P12244/D2/T72] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:41:56,315 [P12244/D2/T88] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:42:00,361 [P12244/D2/T69] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:42:00,376 [P12244/D2/T69] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:42:48,322 [P12244/D2/T7] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:42:52,414 [P12244/D2/T7] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:42:52,430 [P12244/D2/T7] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:43:59,457 [P12244/D2/T75] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 12:47:36,671 [P12244/D2/T11] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:47:40,770 [P12244/D2/T17] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:47:40,787 [P12244/D2/T17] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:47:55,666 [P12244/D2/T17] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:47:59,698 [P12244/D2/T11] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:47:59,725 [P12244/D2/T11] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:49:03,561 [P12244/D2/T38] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 12:50:53,334 [P12244/D2/T50] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:50:57,420 [P12244/D2/T50] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:50:57,446 [P12244/D2/T50] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:51:02,216 [P12244/D2/T44] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:51:06,246 [P12244/D2/T54] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:51:06,271 [P12244/D2/T54] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:51:10,183 [P12244/D2/T49] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:51:14,224 [P12244/D2/T44] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:51:14,246 [P12244/D2/T44] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:53:49,140 [P12244/D2/T76] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:53:53,225 [P12244/D2/T76] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:53:53,248 [P12244/D2/T76] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:54:07,667 [P12244/D2/T104] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 12:54:20,116 [P12244/D2/T78] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:54:24,211 [P12244/D2/T76] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:54:24,228 [P12244/D2/T76] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:55:55,933 [P12244/D2/T85] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:56:00,024 [P12244/D2/T85] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:56:00,056 [P12244/D2/T85] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:56:09,652 [P12244/D2/T107] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:56:13,691 [P12244/D2/T85] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:56:13,704 [P12244/D2/T85] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:56:41,582 [P12244/D2/T138] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:56:45,667 [P12244/D2/T85] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:56:45,681 [P12244/D2/T85] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:57:31,817 [P12244/D2/T85] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:57:35,928 [P12244/D2/T124] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:57:35,946 [P12244/D2/T124] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:59:09,162 [P12244/D2/T124] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:59:11,776 [P12244/D2/T26] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 12:59:13,265 [P12244/D2/T124] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:59:13,292 [P12244/D2/T124] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 12:59:46,316 [P12244/D2/T110] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 12:59:50,394 [P12244/D2/T91] INFO  umbraco.content - Save Xml to file...
 2021-02-05 12:59:50,409 [P12244/D2/T91] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:04:04,078 [P12244/D2/T19] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:04:04,078 [P12244/D2/T19] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:04:04,079 [P12244/D2/T19] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Deploy.IServiceConnector
 2021-02-05 13:04:04,090 [P12244/D2/T19] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Deploy.IServiceConnector (took 11ms)
 2021-02-05 13:04:15,868 [P12244/D2/T93] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:07:41,607 [P13044/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.12.1 application starting on MICROSOFT-PC
 2021-02-05 13:07:41,634 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2021-02-05 13:07:41,649 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 15ms)
 2021-02-05 13:07:41,791 [P13044/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2021-02-05 13:07:41,793 [P13044/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2021-02-05 13:07:41,795 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:42,328 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 533ms)
 2021-02-05 13:07:42,328 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2021-02-05 13:07:42,340 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 11ms)
 2021-02-05 13:07:42,372 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:42,373 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2021-02-05 13:07:42,374 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2021-02-05 13:07:42,387 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 13ms)
 2021-02-05 13:07:42,388 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:42,389 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:42,390 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2021-02-05 13:07:42,404 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 14ms)
 2021-02-05 13:07:42,436 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:42,436 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:42,437 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2021-02-05 13:07:42,460 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 23ms)
 2021-02-05 13:07:42,461 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:42,462 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:42,462 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2021-02-05 13:07:42,479 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 17ms)
 2021-02-05 13:07:44,692 [P13044/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2021-02-05 13:07:44,907 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2021-02-05 13:07:44,922 [P13044/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 14ms)
 2021-02-05 13:07:45,006 [P13044/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2021-02-05 13:07:45,185 [P13044/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2021-02-05 13:07:45,187 [P13044/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2021-02-05 13:07:45,202 [P13044/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 3711ms)
 2021-02-05 13:07:45,208 [P13044/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalMemberIndexSet to be unlocked since it was left in a locked state
 2021-02-05 13:07:45,211 [P13044/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 13:07:45,212 [P13044/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index ExternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 13:07:45,509 [P13044/D2/T6] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost/umbraco
 2021-02-05 13:07:45,512 [P13044/D2/T6] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2021-02-05 13:07:46,064 [P13044/D2/T6] INFO  umbraco.content - Load Xml from file...
 2021-02-05 13:07:46,069 [P13044/D2/T6] INFO  umbraco.content - Loaded Xml from file.
 2021-02-05 13:07:46,770 [P13044/D2/T6] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:46,771 [P13044/D2/T6] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:46,771 [P13044/D2/T6] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 13:07:46,785 [P13044/D2/T6] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 14ms)
 2021-02-05 13:07:50,193 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:50,194 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:50,194 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 13:07:50,215 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 20ms)
 2021-02-05 13:07:50,721 [P13044/D2/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:50,722 [P13044/D2/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2021-02-05 13:07:50,723 [P13044/D2/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2021-02-05 13:07:50,752 [P13044/D2/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 29ms)
 2021-02-05 13:07:52,490 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:52,491 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:52,491 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2021-02-05 13:07:52,517 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 25ms)
 2021-02-05 13:07:52,552 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:52,552 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:52,553 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 13:07:52,553 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2021-02-05 13:07:52,558 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:52,558 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:52,559 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2021-02-05 13:07:52,579 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 19ms)
 2021-02-05 13:07:52,612 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:52,613 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:52,613 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2021-02-05 13:07:52,641 [P13044/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 27ms)
 2021-02-05 13:07:53,340 [P13044/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:07:53,341 [P13044/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:07:53,341 [P13044/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2021-02-05 13:07:53,355 [P13044/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 13ms)
 2021-02-05 13:08:46,159 [P13044/D2/T10] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2021-02-04 13:08:46
 2021-02-05 13:08:50,173 [P13044/D2/T23] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:12:10,790 [P13044/D2/T28] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:12:10,791 [P13044/D2/T28] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:12:10,791 [P13044/D2/T28] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.HealthCheck.HealthCheck
 2021-02-05 13:12:10,815 [P13044/D2/T28] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.HealthCheck.HealthCheck (took 23ms)
 2021-02-05 13:12:29,806 [P13044/D2/T24] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:12:29,806 [P13044/D2/T24] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:12:29,806 [P13044/D2/T24] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2021-02-05 13:12:29,819 [P13044/D2/T24] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 13ms)
 2021-02-05 13:12:29,891 [P13044/D2/T24] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generate models now.
 2021-02-05 13:12:31,208 [P13044/D2/T24] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generated.
 2021-02-05 13:12:42,875 [P13044/D2/T51] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generate models now.
 2021-02-05 13:12:43,024 [P13044/D2/T51] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generated.
 2021-02-05 13:13:29,715 [P13044/D2/T49] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:13:29,716 [P13044/D2/T49] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:13:29,716 [P13044/D2/T49] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Deploy.IServiceConnector
 2021-02-05 13:13:29,729 [P13044/D2/T49] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Deploy.IServiceConnector (took 13ms)
 2021-02-05 13:13:54,275 [P13044/D2/T33] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:15:49,115 [P13044/D2/T32] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:15:53,303 [P13044/D2/T32] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:15:53,321 [P13044/D2/T32] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:18:58,378 [P13044/D2/T91] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:19:28,035 [P13044/D2/T12] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:19:32,154 [P13044/D2/T12] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:19:32,173 [P13044/D2/T12] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:23:12,924 [P13044/D2/T121] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:23:17,014 [P13044/D2/T116] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:23:17,031 [P13044/D2/T116] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:23:57,048 [P13044/D2/T12] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:24:01,141 [P13044/D2/T113] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:24:01,157 [P13044/D2/T113] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:24:02,510 [P13044/D2/T97] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:27:39,203 [P13044/D2/T91] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:27:43,310 [P13044/D2/T85] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:27:43,327 [P13044/D2/T85] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:28:07,473 [P13044/D2/T93] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:28:11,564 [P13044/D2/T91] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:28:11,585 [P13044/D2/T91] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:28:21,804 [P13044/D2/T93] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:28:25,861 [P13044/D2/T91] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:28:25,880 [P13044/D2/T91] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:28:51,591 [P13044/D2/T9] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:28:55,647 [P13044/D2/T14] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:28:55,663 [P13044/D2/T14] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:29:06,597 [P13044/D2/T81] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:29:33,355 [P13044/D2/T121] INFO  Umbraco.Core.Manifest.ManifestWatcher - manifest has changed, app pool is restarting (C:\Users\User_2\source\repos\TestProject\TestProject\App_Plugins\DocTypeGridEditor\package.manifest)
 2021-02-05 13:29:33,370 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Terminating
 2021-02-05 13:29:33,370 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Waiting for tasks to complete
 2021-02-05 13:29:33,374 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Terminating
 2021-02-05 13:29:33,374 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Waiting for tasks to complete
 2021-02-05 13:29:33,376 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Tasks completed, terminated
 2021-02-05 13:29:33,378 [P13044/D2/T131] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Tasks completed, terminated
 2021-02-05 13:29:33,378 [P13044/D2/T114] INFO  Umbraco.Core.MainDom - Stopping...
 2021-02-05 13:29:33,382 [P13044/D2/T114] INFO  Umbraco.Web.ExamineStartup - Examine shutting down
 2021-02-05 13:29:33,396 [P13044/D2/T114] INFO  Umbraco.Web.ExamineStartup - Complete (took 13ms)
 2021-02-05 13:29:33,398 [P13044/D2/T114] INFO  Umbraco.Core.MainDom - Released MainDom.
 2021-02-05 13:29:33,399 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Terminating
 2021-02-05 13:29:33,399 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Waiting for tasks to complete
 2021-02-05 13:29:33,400 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Terminating
 2021-02-05 13:29:33,402 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Waiting for tasks to complete
 2021-02-05 13:29:33,402 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Terminating
 2021-02-05 13:29:33,403 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Waiting for tasks to complete
 2021-02-05 13:29:33,403 [P13044/D2/T131] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Tasks completed, terminated
 2021-02-05 13:29:33,402 [P13044/D2/T90] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Tasks completed, terminated
 2021-02-05 13:29:33,405 [P13044/D2/T111] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Tasks completed, terminated
 2021-02-05 13:29:33,424 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Terminating
 2021-02-05 13:29:33,424 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Waiting for tasks to complete
 2021-02-05 13:29:33,424 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Terminating
 2021-02-05 13:29:33,425 [P13044/D2/T80] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Tasks completed, terminated
 2021-02-05 13:29:33,425 [P13044/D2/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Waiting for tasks to complete
 2021-02-05 13:29:33,427 [P13044/D2/T110] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Tasks completed, terminated
 2021-02-05 13:29:35,566 [P13044/D3/T119] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.12.1 application starting on MICROSOFT-PC
 2021-02-05 13:29:35,591 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2021-02-05 13:29:35,603 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Hash determined (took 12ms)
 2021-02-05 13:29:35,689 [P13044/D3/T119] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2021-02-05 13:29:35,690 [P13044/D3/T119] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2021-02-05 13:29:35,692 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:29:36,336 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 644ms)
 2021-02-05 13:29:36,336 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2021-02-05 13:29:36,337 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 1ms)
 2021-02-05 13:29:36,414 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:29:36,415 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:29:36,415 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2021-02-05 13:29:36,415 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2021-02-05 13:29:36,416 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:29:36,416 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:29:36,416 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2021-02-05 13:29:36,417 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 1ms)
 2021-02-05 13:29:36,442 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:29:36,443 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:29:36,443 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2021-02-05 13:29:36,443 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 0ms)
 2021-02-05 13:29:36,444 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:29:36,444 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:29:36,444 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2021-02-05 13:29:36,445 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 0ms)
 2021-02-05 13:29:38,202 [P13044/D3/T119] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2021-02-05 13:29:38,462 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2021-02-05 13:29:38,507 [P13044/D3/T119] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 45ms)
 2021-02-05 13:29:38,590 [P13044/D3/T119] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2021-02-05 13:29:38,929 [P13044/D3/T119] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2021-02-05 13:29:38,930 [P13044/D3/T119] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2021-02-05 13:29:38,944 [P13044/D3/T119] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 3530ms)
 2021-02-05 13:29:41,136 [P13044/D3/T110] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost/umbraco
 2021-02-05 13:29:41,138 [P13044/D3/T110] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2021-02-05 13:29:41,749 [P13044/D3/T131] INFO  umbraco.content - Load Xml from file...
 2021-02-05 13:29:41,750 [P13044/D3/T131] INFO  umbraco.content - Loaded Xml from file.
 2021-02-05 13:29:42,401 [P13044/D3/T131] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:29:42,401 [P13044/D3/T131] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:29:42,401 [P13044/D3/T131] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 13:29:42,402 [P13044/D3/T131] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 0ms)
 2021-02-05 13:30:03,535 [P13044/D2/T14] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: UnloadAppDomainCalled

_shutDownMessage=User code called UnloadAppDomain
HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown

_shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   at System.Web.HttpRuntime.UnloadAppDomain()
   at Umbraco.Core.Manifest.ManifestWatcher.FswChanged(Object sender, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
 2021-02-05 13:30:29,300 [P13044/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:30:29,301 [P13044/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:30:29,301 [P13044/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2021-02-05 13:30:29,302 [P13044/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 0ms)
 2021-02-05 13:30:29,488 [P13044/D3/T14] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:30:29,599 [P13044/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:30:29,600 [P13044/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:30:29,600 [P13044/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2021-02-05 13:30:29,601 [P13044/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 0ms)
 2021-02-05 13:30:30,417 [P13044/D3/T89] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:30:30,417 [P13044/D3/T89] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:30:30,417 [P13044/D3/T89] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2021-02-05 13:30:30,418 [P13044/D3/T89] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 0ms)
 2021-02-05 13:30:33,765 [P13044/D3/T5] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:30:33,785 [P13044/D3/T5] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:30:41,810 [P13044/D3/T123] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2021-02-04 13:30:41
 2021-02-05 13:30:44,812 [P13044/D3/T14] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:30:45,900 [P13044/D3/T81] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:30:48,854 [P13044/D3/T5] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:30:48,869 [P13044/D3/T5] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:30:58,434 [P13044/D3/T5] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:31:02,481 [P13044/D3/T5] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:31:02,495 [P13044/D3/T5] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:32:23,193 [P13044/D3/T67] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:32:27,313 [P13044/D3/T63] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:32:27,333 [P13044/D3/T63] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:33:23,787 [P13044/D3/T63] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:33:23,787 [P13044/D3/T63] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:33:23,787 [P13044/D3/T63] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 13:33:23,788 [P13044/D3/T63] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2021-02-05 13:33:23,791 [P13044/D3/T63] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:33:23,791 [P13044/D3/T63] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:33:23,792 [P13044/D3/T63] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2021-02-05 13:33:23,792 [P13044/D3/T63] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 0ms)
 2021-02-05 13:33:44,416 [P13044/D3/T124] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:33:44,416 [P13044/D3/T124] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:33:44,416 [P13044/D3/T124] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 13:33:44,417 [P13044/D3/T124] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2021-02-05 13:33:45,112 [P13044/D3/T26] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:33:45,112 [P13044/D3/T26] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:33:45,113 [P13044/D3/T26] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2021-02-05 13:33:45,115 [P13044/D3/T26] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 2ms)
 2021-02-05 13:33:45,128 [P13044/D3/T26] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:33:45,129 [P13044/D3/T26] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:33:45,129 [P13044/D3/T26] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2021-02-05 13:33:45,129 [P13044/D3/T26] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 0ms)
 2021-02-05 13:35:50,014 [P13044/D3/T8] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:40:05,878 [P13044/D3/T106] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:40:05,878 [P13044/D3/T106] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:40:05,879 [P13044/D3/T106] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.HealthCheck.HealthCheck
 2021-02-05 13:40:05,881 [P13044/D3/T106] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.HealthCheck.HealthCheck (took 2ms)
 2021-02-05 13:40:35,480 [P13044/D3/T21] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generate models now.
 2021-02-05 13:40:37,051 [P13044/D3/T21] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generated.
 2021-02-05 13:40:54,109 [P13044/D3/T89] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:40:56,084 [P13044/D3/T95] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:41:00,193 [P13044/D3/T114] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:41:00,216 [P13044/D3/T114] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:41:06,355 [P13044/D3/T95] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:41:10,392 [P13044/D3/T114] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:41:10,412 [P13044/D3/T114] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:45:38,384 [P13044/D3/T69] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generate models now.
 2021-02-05 13:45:38,654 [P13044/D3/T69] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generated.
 2021-02-05 13:45:55,095 [P13044/D3/T107] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:45:58,234 [P13044/D3/T30] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:45:59,189 [P13044/D3/T16] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:45:59,204 [P13044/D3/T16] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:46:13,585 [P13044/D3/T69] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 13:46:17,632 [P13044/D3/T69] INFO  umbraco.content - Save Xml to file...
 2021-02-05 13:46:17,651 [P13044/D3/T69] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 13:51:02,346 [P13044/D3/T24] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 13:52:29,821 [P13044/D3/T39] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 13:52:29,821 [P13044/D3/T39] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 13:52:29,821 [P13044/D3/T39] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Deploy.IServiceConnector
 2021-02-05 13:52:29,823 [P13044/D3/T39] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Deploy.IServiceConnector (took 1ms)
 2021-02-05 14:34:56,658 [P13140/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.12.1 application starting on MICROSOFT-PC
 2021-02-05 14:34:56,683 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2021-02-05 14:34:56,698 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 15ms)
 2021-02-05 14:34:56,829 [P13140/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2021-02-05 14:34:56,832 [P13140/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2021-02-05 14:34:56,835 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:34:57,318 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 483ms)
 2021-02-05 14:34:57,319 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2021-02-05 14:34:57,332 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 13ms)
 2021-02-05 14:34:57,367 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:34:57,368 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:34:57,368 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2021-02-05 14:34:57,382 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 13ms)
 2021-02-05 14:34:57,383 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:34:57,383 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:34:57,384 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2021-02-05 14:34:57,397 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 13ms)
 2021-02-05 14:34:57,416 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:34:57,417 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:34:57,417 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2021-02-05 14:34:57,429 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 11ms)
 2021-02-05 14:34:57,430 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:34:57,431 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:34:57,431 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2021-02-05 14:34:57,444 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 13ms)
 2021-02-05 14:34:59,326 [P13140/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2021-02-05 14:34:59,504 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2021-02-05 14:34:59,517 [P13140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 13ms)
 2021-02-05 14:34:59,592 [P13140/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2021-02-05 14:34:59,762 [P13140/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2021-02-05 14:34:59,763 [P13140/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2021-02-05 14:34:59,774 [P13140/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 3210ms)
 2021-02-05 14:34:59,779 [P13140/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalMemberIndexSet to be unlocked since it was left in a locked state
 2021-02-05 14:34:59,780 [P13140/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 14:34:59,781 [P13140/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index ExternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 14:35:00,018 [P13140/D2/T7] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost/umbraco
 2021-02-05 14:35:00,020 [P13140/D2/T7] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2021-02-05 14:35:00,391 [P13140/D2/T7] INFO  umbraco.content - Load Xml from file...
 2021-02-05 14:35:00,395 [P13140/D2/T7] INFO  umbraco.content - Loaded Xml from file.
 2021-02-05 14:35:01,180 [P13140/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:35:01,181 [P13140/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:35:01,181 [P13140/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 14:35:01,196 [P13140/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 14ms)
 2021-02-05 14:35:01,218 [P13140/D2/T8] INFO  Umbraco.Core.Manifest.ManifestWatcher - manifest has changed, app pool is restarting (C:\Users\User_2\source\repos\TestProject\TestProject\App_Plugins\DocTypeGridEditor\package.manifest)
 2021-02-05 14:35:01,232 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Terminating
 2021-02-05 14:35:01,232 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Waiting for tasks to complete
 2021-02-05 14:35:01,238 [P13140/D2/T12] INFO  Umbraco.Core.MainDom - Stopping...
 2021-02-05 14:35:01,242 [P13140/D2/T14] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Tasks completed, terminated
 2021-02-05 14:35:01,243 [P13140/D2/T12] INFO  Umbraco.Web.ExamineStartup - Examine shutting down
 2021-02-05 14:35:01,250 [P13140/D2/T12] INFO  Umbraco.Web.ExamineStartup - Complete (took 6ms)
 2021-02-05 14:35:01,251 [P13140/D2/T12] INFO  Umbraco.Core.MainDom - Released MainDom.
 2021-02-05 14:35:01,260 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Terminating
 2021-02-05 14:35:01,260 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Waiting for tasks to complete
 2021-02-05 14:35:01,261 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Terminating
 2021-02-05 14:35:01,261 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Waiting for tasks to complete
 2021-02-05 14:35:01,261 [P13140/D2/T14] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Tasks completed, terminated
 2021-02-05 14:35:01,262 [P13140/D2/T16] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Tasks completed, terminated
 2021-02-05 14:35:01,263 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Terminating
 2021-02-05 14:35:01,264 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Waiting for tasks to complete
 2021-02-05 14:35:01,264 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Tasks completed, terminated
 2021-02-05 14:35:01,264 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Terminating
 2021-02-05 14:35:01,265 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Waiting for tasks to complete
 2021-02-05 14:35:01,265 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Terminating
 2021-02-05 14:35:01,265 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Waiting for tasks to complete
 2021-02-05 14:35:01,265 [P13140/D2/T15] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Tasks completed, terminated
 2021-02-05 14:35:01,266 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Terminating
 2021-02-05 14:35:01,266 [P13140/D2/T12] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Waiting for tasks to complete
 2021-02-05 14:35:01,266 [P13140/D2/T14] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Tasks completed, terminated
 2021-02-05 14:35:01,267 [P13140/D2/T16] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Tasks completed, terminated
 2021-02-05 14:35:03,861 [P13140/D2/T11] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:35:03,861 [P13140/D2/T11] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:35:03,861 [P13140/D2/T11] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 14:35:03,877 [P13140/D2/T11] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 15ms)
 2021-02-05 14:35:07,510 [P13140/D3/T17] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.12.1 application starting on MICROSOFT-PC
 2021-02-05 14:35:07,556 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2021-02-05 14:35:07,572 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Hash determined (took 16ms)
 2021-02-05 14:35:07,678 [P13140/D3/T17] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2021-02-05 14:35:07,681 [P13140/D3/T17] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2021-02-05 14:35:07,684 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:35:08,362 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 678ms)
 2021-02-05 14:35:08,363 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2021-02-05 14:35:08,365 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 2ms)
 2021-02-05 14:35:08,464 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:35:08,465 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2021-02-05 14:35:08,466 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2021-02-05 14:35:08,467 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2021-02-05 14:35:08,468 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:35:08,468 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:35:08,469 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2021-02-05 14:35:08,471 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 2ms)
 2021-02-05 14:35:08,495 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:35:08,496 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:35:08,496 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2021-02-05 14:35:08,497 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 0ms)
 2021-02-05 14:35:08,498 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:35:08,499 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:35:08,499 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2021-02-05 14:35:08,501 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 1ms)
 2021-02-05 14:35:10,614 [P13140/D3/T17] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2021-02-05 14:35:10,961 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2021-02-05 14:35:10,963 [P13140/D3/T17] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 1ms)
 2021-02-05 14:35:11,069 [P13140/D3/T17] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2021-02-05 14:35:11,447 [P13140/D3/T17] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2021-02-05 14:35:11,448 [P13140/D3/T17] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2021-02-05 14:35:11,461 [P13140/D3/T17] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 4100ms)
 2021-02-05 14:35:13,683 [P13140/D3/T11] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost/umbraco
 2021-02-05 14:35:13,685 [P13140/D3/T11] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2021-02-05 14:35:14,499 [P13140/D3/T11] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:35:14,500 [P13140/D3/T11] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:35:14,500 [P13140/D3/T11] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2021-02-05 14:35:14,525 [P13140/D3/T11] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 25ms)
 2021-02-05 14:35:14,728 [P13140/D3/T11] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:35:14,728 [P13140/D3/T11] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:35:14,728 [P13140/D3/T11] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 14:35:14,729 [P13140/D3/T11] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 0ms)
 2021-02-05 14:35:31,355 [P13140/D2/T7] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: UnloadAppDomainCalled

_shutDownMessage=User code called UnloadAppDomain
HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown

_shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   at System.Web.HttpRuntime.UnloadAppDomain()
   at Umbraco.Core.Manifest.ManifestWatcher.FswChanged(Object sender, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
 2021-02-05 14:36:14,387 [P13140/D3/T21] INFO  umbraco.content - Load Xml from file...
 2021-02-05 14:36:14,390 [P13140/D3/T21] INFO  umbraco.content - Loaded Xml from file.
 2021-02-05 14:36:14,410 [P13140/D3/T23] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2021-02-04 14:36:14
 2021-02-05 14:36:14,414 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:36:14,414 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:36:14,415 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2021-02-05 14:36:14,446 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 30ms)
 2021-02-05 14:36:18,493 [P13140/D3/T25] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 14:36:27,745 [P13140/D3/T6] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username test@test.test from IP address ::1
 2021-02-05 14:36:27,746 [P13140/D3/T6] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: test@test.test logged in from IP address ::1
 2021-02-05 14:36:28,170 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:36:28,170 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:36:28,170 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 14:36:28,171 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2021-02-05 14:36:28,225 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:36:28,225 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:36:28,225 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2021-02-05 14:36:28,236 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 10ms)
 2021-02-05 14:36:28,253 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:36:28,253 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:36:28,253 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 14:36:28,253 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2021-02-05 14:36:28,259 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:36:28,259 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:36:28,259 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2021-02-05 14:36:28,272 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 12ms)
 2021-02-05 14:36:28,294 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:36:28,295 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:36:28,295 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2021-02-05 14:36:28,307 [P13140/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 11ms)
 2021-02-05 14:36:31,459 [P13140/D3/T22] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:36:31,460 [P13140/D3/T22] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:36:31,460 [P13140/D3/T22] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.HealthCheck.HealthCheck
 2021-02-05 14:36:31,490 [P13140/D3/T22] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.HealthCheck.HealthCheck (took 30ms)
 2021-02-05 14:36:36,856 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:36:36,856 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:36:36,856 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2021-02-05 14:36:36,869 [P13140/D3/T21] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 13ms)
 2021-02-05 14:36:54,173 [P13140/D3/T7] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:36:54,173 [P13140/D3/T7] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:36:54,173 [P13140/D3/T7] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 14:36:54,174 [P13140/D3/T7] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 0ms)
 2021-02-05 14:39:25,777 [P13140/D3/T37] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 14:39:30,002 [P13140/D3/T42] INFO  umbraco.content - Save Xml to file...
 2021-02-05 14:39:30,026 [P13140/D3/T42] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 14:39:35,248 [P13140/D3/T32] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 14:39:39,384 [P13140/D3/T38] INFO  umbraco.content - Save Xml to file...
 2021-02-05 14:39:39,401 [P13140/D3/T38] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 14:41:22,580 [P13140/D3/T60] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 14:43:49,662 [P11040/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.12.1 application starting on MICROSOFT-PC
 2021-02-05 14:43:49,690 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2021-02-05 14:43:49,709 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 19ms)
 2021-02-05 14:43:49,814 [P11040/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2021-02-05 14:43:49,816 [P11040/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2021-02-05 14:43:49,821 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:43:50,303 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 480ms)
 2021-02-05 14:43:50,303 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2021-02-05 14:43:50,318 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 14ms)
 2021-02-05 14:43:50,343 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:43:50,344 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2021-02-05 14:43:50,345 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2021-02-05 14:43:50,361 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 16ms)
 2021-02-05 14:43:50,362 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:43:50,362 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:43:50,363 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2021-02-05 14:43:50,376 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 12ms)
 2021-02-05 14:43:50,398 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:43:50,398 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:43:50,398 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2021-02-05 14:43:50,411 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 12ms)
 2021-02-05 14:43:50,412 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:43:50,412 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:43:50,412 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2021-02-05 14:43:50,428 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 15ms)
 2021-02-05 14:43:52,298 [P11040/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2021-02-05 14:43:52,500 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2021-02-05 14:43:52,516 [P11040/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 17ms)
 2021-02-05 14:43:52,613 [P11040/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2021-02-05 14:43:52,815 [P11040/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2021-02-05 14:43:52,816 [P11040/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2021-02-05 14:43:52,827 [P11040/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 3271ms)
 2021-02-05 14:43:52,832 [P11040/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalMemberIndexSet to be unlocked since it was left in a locked state
 2021-02-05 14:43:52,835 [P11040/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 14:43:52,836 [P11040/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index ExternalIndexSet to be unlocked since it was left in a locked state
 2021-02-05 14:43:53,071 [P11040/D2/T6] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost/umbraco
 2021-02-05 14:43:53,073 [P11040/D2/T6] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2021-02-05 14:43:53,405 [P11040/D2/T6] INFO  umbraco.content - Load Xml from file...
 2021-02-05 14:43:53,408 [P11040/D2/T6] INFO  umbraco.content - Loaded Xml from file.
 2021-02-05 14:43:53,668 [P11040/D2/T6] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.
 2021-02-05 14:44:00,428 [P11040/D2/T6] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:44:00,429 [P11040/D2/T6] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:44:00,429 [P11040/D2/T6] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 14:44:00,464 [P11040/D2/T6] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 34ms)
 2021-02-05 14:44:04,115 [P11040/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:44:04,115 [P11040/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:44:04,116 [P11040/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 14:44:04,137 [P11040/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 21ms)
 2021-02-05 14:44:04,335 [P11040/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:44:04,336 [P11040/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:44:04,336 [P11040/D2/T7] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2021-02-05 14:44:04,364 [P11040/D2/T7] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 28ms)
 2021-02-05 14:44:05,408 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:44:05,408 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:44:05,409 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2021-02-05 14:44:05,429 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 20ms)
 2021-02-05 14:44:05,458 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:44:05,459 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2021-02-05 14:44:05,460 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2021-02-05 14:44:05,461 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2021-02-05 14:44:05,467 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:44:05,467 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:44:05,468 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2021-02-05 14:44:05,488 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 20ms)
 2021-02-05 14:44:05,572 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:44:05,573 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:44:05,573 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2021-02-05 14:44:05,612 [P11040/D2/T9] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 38ms)
 2021-02-05 14:44:06,316 [P11040/D2/T11] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:44:06,316 [P11040/D2/T11] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:44:06,316 [P11040/D2/T11] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2021-02-05 14:44:06,348 [P11040/D2/T11] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 31ms)
 2021-02-05 14:44:53,489 [P11040/D2/T10] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2021-02-04 14:44:53
 2021-02-05 14:44:57,544 [P11040/D2/T21] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 14:45:42,334 [P11040/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:45:42,334 [P11040/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:45:42,334 [P11040/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.HealthCheck.HealthCheck
 2021-02-05 14:45:42,355 [P11040/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.HealthCheck.HealthCheck (took 20ms)
 2021-02-05 14:45:48,505 [P11040/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:45:48,505 [P11040/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:45:48,505 [P11040/D2/T8] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2021-02-05 14:45:48,505 [P11040/D2/T8] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 0ms)
 2021-02-05 14:45:55,303 [P11040/D2/T6] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:45:55,303 [P11040/D2/T6] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:45:55,303 [P11040/D2/T6] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2021-02-05 14:45:55,314 [P11040/D2/T6] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 11ms)
 2021-02-05 14:46:49,601 [P11040/D2/T30] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 14:46:51,541 [P11040/D2/T33] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2021-02-05 14:46:51,542 [P11040/D2/T33] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2021-02-05 14:46:51,542 [P11040/D2/T33] INFO  Umbraco.Core.PluginManager - Resolving umbraco.cms.businesslogic.macro.IMacroEngine
 2021-02-05 14:46:51,556 [P11040/D2/T33] INFO  Umbraco.Core.PluginManager - Resolved umbraco.cms.businesslogic.macro.IMacroEngine (took 13ms)
 2021-02-05 14:46:53,816 [P11040/D2/T28] INFO  umbraco.content - Save Xml to file...
 2021-02-05 14:46:53,835 [P11040/D2/T28] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 14:50:01,685 [P11040/D2/T42] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 14:55:05,747 [P11040/D2/T119] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 14:56:12,417 [P11040/D2/T102] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 14:56:16,516 [P11040/D2/T115] INFO  umbraco.content - Save Xml to file...
 2021-02-05 14:56:16,550 [P11040/D2/T115] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 14:57:32,729 [P11040/D2/T131] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 14:57:36,847 [P11040/D2/T121] INFO  umbraco.content - Save Xml to file...
 2021-02-05 14:57:36,861 [P11040/D2/T121] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 15:00:01,385 [P11040/D2/T153] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generate models now.
 2021-02-05 15:00:02,726 [P11040/D2/T153] INFO  Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider - Generated.
 2021-02-05 15:00:09,836 [P11040/D2/T139] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 15:00:14,052 [P11040/D2/T153] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 15:00:18,172 [P11040/D2/T153] INFO  umbraco.content - Save Xml to file...
 2021-02-05 15:00:18,192 [P11040/D2/T153] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 15:04:24,966 [P11040/D2/T103] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 15:04:29,124 [P11040/D2/T93] INFO  umbraco.content - Save Xml to file...
 2021-02-05 15:04:29,142 [P11040/D2/T93] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 15:05:13,909 [P11040/D2/T104] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 15:05:25,686 [P11040/D2/T81] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 15:05:29,806 [P11040/D2/T95] INFO  umbraco.content - Save Xml to file...
 2021-02-05 15:05:29,825 [P11040/D2/T95] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 15:06:17,744 [P11040/D2/T142] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 15:06:21,862 [P11040/D2/T89] INFO  umbraco.content - Save Xml to file...
 2021-02-05 15:06:21,879 [P11040/D2/T89] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 15:07:55,684 [P11040/D2/T133] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 15:07:59,805 [P11040/D2/T150] INFO  umbraco.content - Save Xml to file...
 2021-02-05 15:07:59,837 [P11040/D2/T150] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 15:08:52,533 [P11040/D2/T151] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 15:08:56,683 [P11040/D2/T69] INFO  umbraco.content - Save Xml to file...
 2021-02-05 15:08:56,707 [P11040/D2/T69] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 15:09:21,387 [P11040/D2/T139] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home Page' with Id '1055' has been published.
 2021-02-05 15:09:25,508 [P11040/D2/T69] INFO  umbraco.content - Save Xml to file...
 2021-02-05 15:09:25,532 [P11040/D2/T69] INFO  umbraco.content - Saved Xml to file.
 2021-02-05 15:10:18,011 [P11040/D2/T111] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 15:15:22,121 [P11040/D2/T111] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 15:19:57,920 [P11040/D2/T50] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.InvalidOperationException: Could not find a Surface controller route in the RouteTable for controller name ContactForm
   at Umbraco.Web.Mvc.RenderRouteHandler.HandlePostedValues(RequestContext requestContext, PostedDataProxyInfo postedInfo)
   at Umbraco.Web.Mvc.RenderRouteHandler.GetHandlerForRoute(RequestContext requestContext, PublishedContentRequest publishedContentRequest)
   at Umbraco.Web.Mvc.RenderRouteHandler.GetHttpHandler(RequestContext requestContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at Umbraco.Web.UmbracoModule.RewriteToUmbracoHandler(HttpContextBase context, PublishedContentRequest pcr)
   at Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext)
   at Umbraco.Web.UmbracoModule.<Init>b__12_2(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 2021-02-05 15:20:02,452 [P11040/D2/T24] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.InvalidOperationException: Could not find a Surface controller route in the RouteTable for controller name ContactForm
   at Umbraco.Web.Mvc.RenderRouteHandler.HandlePostedValues(RequestContext requestContext, PostedDataProxyInfo postedInfo)
   at Umbraco.Web.Mvc.RenderRouteHandler.GetHandlerForRoute(RequestContext requestContext, PublishedContentRequest publishedContentRequest)
   at Umbraco.Web.Mvc.RenderRouteHandler.GetHttpHandler(RequestContext requestContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at Umbraco.Web.UmbracoModule.RewriteToUmbracoHandler(HttpContextBase context, PublishedContentRequest pcr)
   at Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext)
   at Umbraco.Web.UmbracoModule.<Init>b__12_2(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 2021-02-05 15:20:25,725 [P11040/D2/T42] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.InvalidOperationException: Could not find a Surface controller route in the RouteTable for controller name ContactForm
   at Umbraco.Web.Mvc.RenderRouteHandler.HandlePostedValues(RequestContext requestContext, PostedDataProxyInfo postedInfo)
   at Umbraco.Web.Mvc.RenderRouteHandler.GetHandlerForRoute(RequestContext requestContext, PublishedContentRequest publishedContentRequest)
   at Umbraco.Web.Mvc.RenderRouteHandler.GetHttpHandler(RequestContext requestContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at Umbraco.Web.UmbracoModule.RewriteToUmbracoHandler(HttpContextBase context, PublishedContentRequest pcr)
   at Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext)
   at Umbraco.Web.UmbracoModule.<Init>b__12_2(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 2021-02-05 15:20:26,249 [P11040/D2/T22] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
 2021-02-05 15:25:30,359 [P11040/D2/T22] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
